### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by reaper666735** [funkydude/BasicChatMods#4]
i will just copy the link to the curseforge ticket :p , not sure what site issue's/suggestions are being handled ... , 

[https://wow.curseforge.com/projects/basic-chat-mods/issues/50](url)

**Comment by funkydude** [comment]
Please look in the GUI prior to opening 2 tickets. It's called "class colours" in the "player names" section.

**Comment by reaper666735** [comment]
my apologies, i was unaware you had to Enable the module so you can disable that feature... , 

i simply disabled the whole Players Names module and saw the colouring, so i assumed it was always on :(

**Comment by funkydude** [comment]
BCM just turns on the Blizz name colouring. What you can do is enable the module, disable the option, and disable the module again.

Literally all it does is cycle through all the settings and enable/disable colouring. You can do this yourself by right clicking a chat tab and selecting settings.

I could have it disable all the colours when disabling the module, but since this is a Blizz option most people have enabled even prior to installing BCM, they would blame BCM for "permanently disabling" their colours.
